tsharon-byte/28_mf_teamwork_01

packages/client/src/App.test.tsx, packages/client/src/App.tsx
=> 28-11 проверка хуков прекоммита и PR

packages/client/package.json, yarn.lock
Необходимо добавить в проект базовые компоненты.
Установлен Material UI
=> added material ui package

packages/client/package.json, packages/client/src/components/error/index.tsx, packages/client/src/components/index.ts, packages/client/src/pages/error-page/helpers.ts, packages/client/src/pages/error-page/index.tsx, packages/client/src/pages/error-page/types.ts, packages/client/src/utils/router.tsx, yarn.lock
Необходимо настроить обработку ошибок внутри «детей» React-компонентов.
Обработка ошибок выполняется из коробки в react-router-dom.
1. Добавлена страница ErrorPage, которая рендерится во время возникновения ошибки в компоненте или дочерних компонентах.
2. Добавлен пакет react-error-boundary. В случае, если необходимо для какого-то определенного компонента вывести особую ошибку, можно воспользоваться функционалом этой библиотеки.
https://github.com/bvaughn/react-error-boundary
=> added error handling inside children

package-lock.json, packages/client/.env.development, yarn.lock
Добавлены переменные окружения для development режима
=> Добавлены переменные окружения для development режима

packages/client/src/components/protected-route/index.tsx
Поправлен переход на страницы с авторизацией
=> Поправлен переход на страницы с авторизацией

packages/client/package.json, packages/client/src/components/bomberman/index.tsx, packages/client/src/utils/useFullScreen.ts, packages/client/src/utils/utils.ts, yarn.lock
Добавлено одно из описанных в уроках Web API: - Fullscreen API
Добавлена кнопка полноэкранного режима на экране с игрой
Размещение кнопки поправлю когда добавлю стартовый экран игры
=> 28-39: Добавлено одно из описанных в уроках Web API: - Fullscreen API

packages/client/src/components/protected-route/index.tsx, packages/client/src/hooks/use-auth/index.ts, packages/client/src/hooks/use-user/index.ts, packages/client/src/store/slices/user-slice/index.ts
- Необходимо исправить хук useUser, чтобы не происходили лишние запросы, когда пользователь уже есть в хранилище.
- Необходимо исправить проблему навигации при переходе неавторизованного пользователя на защищенные роуты. Переход на защищенный роут не должен происходить, если пользователь не авторизован.
=> fixed use user hook and protected route component

.eslintrc.js, lefthook.yml, packages/client/src/components/bomberman/bomberman.css, packages/client/src/components/bomberman/index.tsx, packages/client/src/components/end-game/EndGame.css, packages/client/src/components/end-game/EndGame.tsx, packages/client/src/components/end-game/EndGamePropsType.d.ts, packages/client/src/pages/game/Game.css, packages/client/src/pages/game/index.tsx, packages/client/src/utils/animation/HeroSprite.ts, packages/client/src/utils/animation/HeroSpriteOptions.d.ts, packages/client/src/utils/animation/helpers.test.ts, packages/client/src/utils/animation/helpers.ts
Реализовать состояние «Начало» и состояние «Завершение игры».
Добавлено диалоговое окно на Успешное/Неуспешное завершение игры
=> 28-35 Реализовать состояние «Начало» и состояние «Завершение игры».

lefthook.yml, packages/client/src/components/bomberman/index.tsx, packages/client/src/store/slices/forum-slice/thunks/create-chat-thunk/index.ts, packages/client/src/store/slices/user-slice/helpers.ts, packages/client/src/store/slices/user-slice/index.ts, packages/client/src/utils/localStorageHelper.ts
Сейчас при перезагрузке страницы очищается стор, поэтому пользователь редиректится на страницу логина каждый раз при перезагрузке.
Эта проблема мешает очищению поля игры по завершению(выигрыш/проигрыш)
Добавила инициализацию стора из LocalStorage
=> add data to localStorage

packages/client/.env.development, packages/client/.env.production, packages/client/src/components/index.ts, packages/client/src/components/profile-components/profile-info/index.tsx, packages/client/src/components/yandex-login/constants.ts, packages/client/src/components/yandex-login/index.tsx, packages/client/src/components/yandex-login/styles.module.css, packages/client/src/helpers/index.ts, packages/client/src/helpers/is-reason-error/index.ts, packages/client/src/helpers/is-reason-error/types.ts, packages/client/src/helpers/prepare-error/index.ts, packages/client/src/helpers/prepare-error/types.ts, packages/client/src/hooks/index.ts, packages/client/src/hooks/use-oauth/constants.ts, packages/client/src/hooks/use-oauth/index.ts, packages/client/src/icons/index.ts, packages/client/src/icons/yandex-icon/index.tsx, packages/client/src/pages/home/index.tsx, packages/client/src/pages/login/index.tsx, packages/client/src/pages/login/styles.module.css, packages/client/src/themes/dark-theme.ts, yarn.lock
Необходимо добавить OAuth-авторизацию в проект.
=> added yandex oauth

packages/client/src/components/app/index.tsx
Добавил роут для ошибки сервера код 500
=> Добавил 500 роут

packages/client/src/components/bomberman/index.test.tsx, packages/client/src/components/bomberman/index.tsx, packages/client/src/hooks/use-music-player/index.ts
[Добавил Web Media API и выделил в отдельный Hook](https://github.com/tsharon-byte/28_mf_teamwork_01/pull/42)
=> 28-46 Добавить ещё одно WEB API (кроме Canvas, Fetch)

packages/client/.env.production
Исправлено redirect_uri для production
=> Исправлено redirect_uri для production

packages/client/src/pages/forum/index.tsx
Не всегда передавалось описание в запрос
=> Поправил ошибку записи описания в бд

packages/client/src/components/topic-components/topic-comment-list/index.tsx, packages/client/src/components/topic-components/topic-comment-list/types.ts, packages/client/src/pages/forum-topic/index.tsx
Поправил вывод описания в топике форума
=> 28-75 Поправил вывод описания в топике форума

packages/client/src/components/topic-components/topic-text-field/index.tsx
Поправил вывод аватарки в форме отправки комментов
=> 28-77 Поправил вывод аватарки в форме отправки комментов

packages/client/src/components/profile-components/profile-avatar/index.tsx, packages/client/src/components/profile-components/profile-avatar/styles.module.css
Нужно убрать кнопку удаления аватарки пользователя, т.к. апи для данного функционала нет.
Кнопку загрузки новой аватарки можно поместить по центру аватарки, добавив backdrop.
=> Убрал кнопку удаления аватарки пользователя

packages/client/src/components/profile-components/edit-text-field/index.tsx, packages/client/src/constants/urls.ts, packages/client/src/hooks/use-user/index.ts, packages/client/src/pages/profile/index.tsx, packages/client/src/store/slices/user-slice/index.ts, packages/client/src/store/slices/user-slice/thunks/index.ts, packages/client/src/store/slices/user-slice/thunks/update-user-thunk/index.ts
Не срабатывают кнопки сохранения изменений.
=> Исправил редактирование в профиле пользователя

packages/client/src/components/topic-components/topic-comment-item/index.tsx, packages/client/src/pages/forum/index.tsx, packages/client/src/store/slices/comments-slice/actions/index.ts, packages/client/src/store/slices/comments-slice/index.ts, packages/client/src/store/slices/forum-slice/actions/index.ts, packages/client/src/store/slices/forum-slice/index.ts
Поправил вывод ошибки в модальной форме отправки сообщения и коммента
=> 28-73 Зависание ошибки в модальной форме

packages/client/src/pages/leaderboard/index.tsx
Выровнять бомбы на доске лидеров
Было
Стало
=> Выровнял бомбы на доске лидеров

packages/client/src/hooks/use-user/index.ts, packages/client/src/store/slices/user-slice/index.ts, packages/client/src/store/slices/user-slice/thunks/change-avatar-thunk/index.ts, packages/client/src/utils/http-transport.ts
Если загрузить слишком большую картинку, возникнет ошибка, но она никак не отобразится в интерфейсе
=> Добавлено отображение ошибок при загрузке аватара пользователя

packages/client/src/components/forum-components/topic-item/index.tsx, packages/client/src/store/slices/forum-slice/types.ts
Приложение падало на странице forum, тк изменили пропс createdAt
=> Приложение падало, тк изменили пропс createdAt

packages/client/src/hooks/use-auth/index.ts, packages/client/src/hooks/use-oauth/index.ts, packages/client/src/hooks/use-user/index.ts, packages/client/src/pages/profile/index.tsx, packages/server/middlewares/auth-middleware.ts, packages/server/server.ts
Реализовать проверку авторизации на бекэнде:
- Реализовать middleware, который проверяет, авторизован ли пользователь.
- Добавить middleware перед всеми ручками.
Можно поставить console.log внутри authMiddleware и убедиться, что все запросы (кроме авторизации) проходят через этот мидлвар. Внутри происходит запрос пользователя и если пользователь авторизован, то выполняется next, в противном случае возвращается ошибка авторизации.
=> Реализация проверки  авторизации на бекенде

packages/client/src/components/protected-route/index.tsx
Бесконенчное получение юзера в протектед роутер
=> Бесконенчное получение юзера

packages/client/src/components/topic-components/topic-comment-list/index.tsx, packages/client/src/components/topic-components/topic-comment-list/styles.module.css
Нужно выровнять аватарку относительно логина
Добавил стили для выравнивания
=> Исправлено выравнивание аватарки топика

packages/client/src/components/app/index.tsx
Не работает роут 404
Добавлен роут для страницы 404
=> Добавлен роут для страницы 404

packages/client/index.html, packages/client/src/pages/forum-topic/index.tsx
Если зайти на страницу топика и перезагрузить её, то получаем просто черный экран
=> Исправлена проблема черного экрана после перезагрузки страницы топика

packages/client/src/components/forum-components/search-and-select-box/index.tsx, packages/client/src/components/forum-components/search-and-select-box/styles.module.css, packages/client/src/themes/theme.ts
Для выпадающего списка нужно убрать backdrop.
Провел небольшую корректировку стилей.
=> Убрал backdrop для выпадающего списка

packages/client/.env.development
=> поправил env для dev

packages/server/server.ts
CSP в настройках сервера. X-Powered-By отключен
=> 28-56 Добавить CSP

packages/client/src/components/bomberman/index.tsx
Сделан кнопку старт не активной если игра уже запущена, т.к. иначе фокус остается на кнопке Старт и пробел запускает функцию старт заново
=> Баг с повторным запуском музыки
